# Generated by Django 5.1.2 on 2024-11-04 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("alumno", "0001_initial"),
        ("profesor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cursada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alumnos", models.ManyToManyField(to="alumno.alumno")),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesor.profesor",
                    ),
                ),
            ],
        ),
    ]
