# Generated by Django 5.1.2 on 2024-11-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("dni", models.CharField(max_length=9)),
                ("fecha_nacimiento", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=9)),
            ],
        ),
    ]
